# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d54ff20af24655ec7cedda23c5977417a9684d7ba295c9fec21f87386383d7be5a71d22137664bd4d9964926976edcb9ebdb8c241417f4aa4fa7f16feab82122

test:
  secret_key_base: 0d9c3044f60e10a76fe33f23e728d2d4cbba826920679a0edc2a073c818b689ef6d47b7944812557a05de474a5732a43f0ff3de78d3f828825bff30bf4eb8d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
